[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["crates/renderer", "crates/state", "crates/freya", "crates/elements", "crates/components", "crates/hooks", "crates/common", "crates/core", "crates/testing", "crates/devtools", "crates/torin", "crates/engine", "./examples/installer",  "crates/native-core",  "crates/native-core-macro"]

[features]
log = ["freya/log"]
devtools = ["freya/devtools"]
use_camera = ["freya/use_camera"]
hot-reload = ["freya/hot-reload"]
custom-tokio-rt = ["freya/custom-tokio-rt"]

[patch.crates-io]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-rsx = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-hooks = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-signals = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-hot-reload = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-lib = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
generational-box = { git = "https://github.com/DioxusLabs/dioxus", rev = "0bb81aba6eeb36df96b3e6943288fa3a2cc25cdd" }
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", branch = "feat/dioxus-0.6" }

[workspace.dependencies]
freya = { path = "crates/freya", version = "0.2" }
freya-devtools = { path = "crates/devtools", version = "0.2" }
freya-node-state = { path = "crates/state", version = "0.2" }
freya-renderer = { path = "crates/renderer", version = "0.2" }
freya-elements = { path = "crates/elements", version = "0.2" }
freya-common = { path = "crates/common", version = "0.2" }
freya-hooks = { path = "crates/hooks", version = "0.2" }
freya-core = { path = "crates/core", version = "0.2" }
freya-components = { path = "crates/components", version = "0.2" }
freya-testing = { path = "crates/testing", version = "0.2" }
freya-engine = { path = "crates/engine", version = "0.2" }
torin = { path = "crates/torin", version = "0.2" }

freya-native-core-macro = { path = "crates/native-core-macro", version = "0.2" }
freya-native-core = { path = "crates/native-core", version = "0.2" }

dioxus = { version = "0.6.0-alpha.2" , default-features = false, features = ["macro", "signals", "hooks"] }
dioxus-rsx =  { version = "0.6.0-alpha.2" }
dioxus-core-macro =  { version = "0.6.0-alpha.2" }
dioxus-hooks = { version = "0.6.0-alpha.2" }
dioxus-signals =  { version = "0.6.0-alpha.2" }
dioxus-core =  { version = "0.6.0-alpha.2" }
dioxus-hot-reload =  { version = "0.6.0-alpha.2" }
dioxus-router =  { version = "0.6.0-alpha.2", default-features = false }
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", branch = "feat/dioxus-0.6", features = ["clipboard"]}

skia-safe = { version = "0.75.0", features = ["gl", "textlayout", "svg"] }

gl = "0.14.0"
glutin = "0.32.0"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.0"
winit = "0.30.0"
tokio = { version = "1.33.0", features = ["sync", "rt-multi-thread", "time", "macros"] }
accesskit = { version = "0.16.0", features = ["serde"]}
accesskit_winit = "0.22.0"
shipyard = { version = "0.6.2", features = ["proc", "std", "parallel"], default-features = false }
smallvec = "1.13.1"

euclid = "0.22.9"
uuid = { version = "1.4.1", features = ["v4"]}
futures-util = "0.3.30"
futures-task = "0.3.30"
tracing = "0.1"
tracing-subscriber = "0.3.17"
rustc-hash = "2.0.0"

[dev-dependencies]
skia-safe = { workspace = true }
tokio = { workspace = true, features = ["fs"]}
dioxus = { workspace = true }
freya = { workspace = true }
freya-core = { workspace = true }
freya-testing = { workspace = true }
reqwest = { version = "0.12.0", features = ["json"] }
serde = "1.0.189"
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", branch = "feat/dioxus-0.6",  features = ["i18n"] }
rand = "0.8.5"
dioxus-router = { workspace = true }
itertools = "0.13.0"
home = "0.5.9"
dioxus-query = "0.5.1"

[profile.release]
lto = true
opt-level = 3
